MeritocrateBundle\Entity\Discussion:
    type: entity
    table: null
    repositoryClass: MeritocrateBundle\Repository\DiscussionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        datecreation:
            type: datetimetz
    oneToMany:
        merits:
            targetEntity: MeritocrateBundle\Entity\Merits
            mappedBy: discussion

