MeritocrateBundle\Entity\Merits:
    type: entity
    table: null
    repositoryClass: MeritocrateBundle\Repository\MeritsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        datecreation:
            type: datetimetz
    manyToOne:
        rator:
            targetEntity: MeritocrateBundle\Entity\User
            inversedBy: merits
        speech:
            targetEntity: MeritocrateBundle\Entity\Speech
            inversedBy: merits