MeritocrateBundle\Entity\Rator:
    type: entity
    table: null
    repositoryClass: MeritocrateBundle\Repository\RatorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        merits:
            targetEntity: MeritocrateBundle\Entity\Merits
            mappedBy: rator
    manyToOne:
        user:
            targetEntity: MeritocrateBundle\Entity\User
            inversedBy: rators