MeritocrateBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: MeritocrateBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fullname:
            type: string
            length: 255
        dateofbirth:
            type: date
            nullable: true
        gender:
            type: string
            length: 255
            nullable: true
        nationality:
            type: string
            length: 255
            nullable: true
        ethnicity:
            type: string
            length: 255
            nullable: true
        picture:
            type: string
            length: 255
            nullable: true
    oneToMany:
        merits:
            targetEntity: MeritocrateBundle\Entity\Merits
            mappedBy: user
        speeches:
            targetEntity: MeritocrateBundle\Entity\Speech
            mappedBy: user
        rators:
            targetEntity: MeritocrateBundle\Entity\Rator
            mappedBy: user