<?php

namespace MeritocrateBundle\Repository;

/**
 * AssemblyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssemblyRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindBy($user){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a.date, a.text, a.attachment')
            ->from('MeritocrateBundle:Assembly', 'a')
            ->join('a.user', 'u')
            ->addSelect('u.id as userId, u.username')
            ->where('a.user = :user')
            ->setParameter('user', $user);
        return $qb->getquery()->getResult();
    }
}
