<?php

namespace MeritocrateBundle\Repository;

/**
 * MeritsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeritsRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyFindMerits($speech){
        $qb = $this->createQueryBuilder('m');
        $qb->where('m.speech = :speech')
           ->setParameter('speech', $speech);
        return $qb->getQuery()->getResult();
    }
}
