<?php

namespace MeritocrateBundle\Repository;

/**
 * MeritsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeritsRepository extends \Doctrine\ORM\EntityRepository
{
}
