<?php

namespace MeritocrateBundle\Repository;

/**
 * PrivateAssemblyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivateAssemblyRepository extends \Doctrine\ORM\EntityRepository
{
}
