<?php

namespace MeritocrateBundle\Repository;

/**
 * PrivateAssemblyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivateAssemblyRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindBy($privateChat){
        $qb = $this->createQueryBuilder('pa');
        $qb->where('pa.privatechat = :privatechat')
            ->setParameter('privatechat', $privateChat);
        return $qb->getquery()->getResult();
    }
}
