<?php

namespace MeritocrateBundle\Repository;

/**
 * PrivateChatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivateChatRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindBy($user, $userClicked){
        $qb = $this->createQueryBuilder('pc');
        $qb->where('pc.creator = :creator')
            ->andWhere('pc.classmate = :classmate')
            ->setParameters(array(
                'creator' => $user,
                'classmate' => $userClicked
            ));
        return $qb->getQuery()->getResult();
    }
}
