<?php

namespace MeritocrateBundle\Repository;

/**
 * RatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatorRepository extends \Doctrine\ORM\EntityRepository
{
}
