<?php

namespace MeritocrateBundle\Repository;

/**
 * SpeechRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeechRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll($discussion){
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.discussion = :discussion')->setParameter('discussion', $discussion);
        return $qb->getQuery()->getResult();
    }

    public function myFindBefore($idLastSpeech, $discussion){
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.id < :start')->setParameter('start', $idLastSpeech)
            ->AndWhere('s.discussion = :discussion')->setParameter('discussion', $discussion);
        return $qb->getQuery()->getResult();
    }

    public function myFindBy($idLastSpeech, $discussion, $max)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.id > :start')->setParameter('start', $idLastSpeech)
           ->AndWhere('s.discussion = :discussion')->setParameter('discussion', $discussion)
           ->setMaxResults($max);
        return $qb->getQuery()->getResult();
    }
}
