<?php

namespace MeritocrateBundle\Repository;

/**
 * SpeechRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeechRepository extends \Doctrine\ORM\EntityRepository
{
}
