<?php

namespace MeritocrateBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll(){
        $qb = $this->createQueryBuilder('u');
        $qb->select('u.id, u.fullname, u.online');
        return $qb->getQuery()->getResult();
    }
}
