meritocrate_homepage:
    path:     /
    defaults: { _controller: MeritocrateBundle:Default:index }

meritocrate_admin:
    path:     /home
    defaults: { _controller: MeritocrateBundle:Default:board }

meritocrate_register:
    path:     /register
    defaults: { _controller: MeritocrateBundle:Registration:register }

meritocrate_new_discussion:
    path:     /home/new
    defaults: { _controller: MeritocrateBundle:Default:newDiscussion }

meritocrate_join_discussion:
    path:     /home/join
    defaults: { _controller: MeritocrateBundle:Default:joinDiscussion }

meritocrate_discussion_group:
    path:     /home/discussion/{id}
    defaults: { _controller: MeritocrateBundle:Default:discussionGroup }
    requirements:
        id: \d+

meritocrate_group_statistics:
    path:     /home/statistics/{id}
    defaults: { _controller: MeritocrateBundle:Default:groupStatistics }

meritocrate_group_livechat:
    path: /home/discussion/livechat/{id}/{identification}
    defaults: { _controller: MeritocrateBundle:Default:groupLivechat, identification: false }

meritocrate_group_livechat_check_access:
    path: /home/discussion/livechat/{idGroup}
    defaults: { _controller: MeritocrateBundle:Default:groupLivechatCheckAccess }

meritocrate_group_new_messages:
    path: /newMessages
    defaults: { _controller: MeritocrateBundle:Default:getNewMessages }

meritocrate_set_speaker:
    path:     /speaks
    defaults: { _controller: MeritocrateBundle:Default:setSpeaker }

meritocrate_get_speakers:
    path:     /speakersList
    defaults: { _controller: MeritocrateBundle:Default:getSpeech }

meritocrate_add_merit:
    path:     /addMerit
    defaults: { _controller: MeritocrateBundle:Default:addMerit }

meritocrate_user_settings:
    path:     /home/settings
    defaults: {_controller: MeritocrateBundle:Default:userSettings }

meritocrate_user_discussion_settings:
    path:     /home/discussions/settings
    defaults: {_controller: MeritocrateBundle:Default:userSettings }

meritocrate_discussion_update:
    path:     /updateDiscussion
    defaults: {_controller: MeritocrateBundle:Default:getUserDiscussionGroup }