meritocrate_homepage:
    path:     /
    defaults: { _controller: MeritocrateBundle:Default:index }

meritocrate_admin:
    path:     /admin
    defaults: { _controller: MeritocrateBundle:Default:board }

meritocrate_register:
    path:     /register
    defaults: { _controller: MeritocrateBundle:Registration:register }

meritocrate_new_discussion:
    path:     /admin/new
    defaults: { _controller: MeritocrateBundle:Default:newDiscussion }

meritocrate_join_discussion:
    path:     /admin/join
    defaults: { _controller: MeritocrateBundle:Default:joinDiscussion }

meritocrate_discussion_group:
    path:     /admin/discussion/{id}
    defaults: { _controller: MeritocrateBundle:Default:discussionGroup }
    requirements:
        id: \d+

meritocrate_group_statistics:
    path:     /admin/statistics/{id}
    defaults: { _controller: MeritocrateBundle:Default:groupStatistics }

meritocrate_set_speaker:
    path:     /speaks
    defaults: { _controller: MeritocrateBundle:Default:setSpeaker }

meritocrate_get_speakers:
    path:     /speakersList
    defaults: { _controller: MeritocrateBundle:Default:getSpeech }

meritocrate_add_merit:
    path:     /addMerit
    defaults: { _controller: MeritocrateBundle:Default:addMerit }

meritocrate_user_settings:
    path:     /admin/settings
    defaults: {_controller: MeritocrateBundle:Default:userSettings }

meritocrate_user_discussion_settings:
    path:     /admin/discussions/settings
    defaults: {_controller: MeritocrateBundle:Default:getUserDiscussionGroup }

meritocrate_discussion_update:
    path:     /updateDiscussion
    defaults: {_controller: MeritocrateBundle:Default:getUserDiscussionGroup }